#
# Steps for building and testing Jest. See jobs defined in .azure-pipelines.yml
#

# Clones the repo
steps:
  - checkout: self

  # Ensure Node.js 10 is active
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Use Node.js 10'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false

  # build project
  - script: npm run build
    displayName: 'Run Build'

    # test project
  - script: npm run test:ci-unit
    displayName: 'Run CI Unit Tests'

  - powershell: |
      $flag = "$(Agent.OS)".toLower() + "unit"
      npx codecov -t $env:TOKEN -F $flag
    displayName: 'Publish codecov'
    env:
      TOKEN: $(CODE_COV_GENERATOR_NK)

  # Publish CI test results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '*junit.xml'
      testRunTitle: 'CI Tests Unit $(Agent.OS)'
    displayName: 'Publish test results'
    condition: succeededOrFailed()

  # test project
  - script: npm run test:ci-e2e
    displayName: 'Run CI E2E Tests'

  - powershell: |
      $flag = "$(Agent.OS)".toLower() + "e2e"
      npx codecov -t $env:TOKEN -F $flag
    displayName: 'Publish codecov'
    env:
      TOKEN: $(CODE_COV_GENERATOR_NK)

  # Publish CI test results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '*junit.xml'
      testRunTitle: 'CI Tests E2E $(Agent.OS)'
    displayName: 'Publish test results'
    condition: succeededOrFailed()
