steps:
  - template: common-steps.yml
  - ${{if eq(variables['Build.SourceBranch'], 'refs/heads/master')}}:

#    - task: Npm@1
#      inputs:
#        command: publish
#        workingDir: build
#        publishEndpoint: npm
#
#      condition: succeeded()

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/src'
        artifactName: 'generator-nk-src'
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
