steps:
  - template: common-steps.yml
  - ${{if eq(variables['Build.SourceBranch'], 'refs/heads/master')}}:

    - task: Npm@1
      inputs:
        command: publish
        workingDir: build
        publishEndpoint: npm

      condition: succeeded()
